// Generated by https://quicktype.io

export interface ResultJurisdiccion {
    ok:   boolean;
    msg:  string;
    resp: Resp[];
}

export interface Resp {
    id:      number;
    nombre:  string;
    estado:  number;
}
